export const path = {
  HOME: "/",

  // Admin
  LOGIN: "/login",
  LOG_OUT: "/logout",
  SYSTEM: "/system",
  MANAGE_USER: "/system/manage-user",
  MANAGE_DOCTOR: "/system/manage-doctor",
  MANAGE_SCHEDULE: "/system/manage-schedule",
  MANAGE_CLINIC: "/system/manage-clinic",
  MANAGE_SPECIALTY: "/system/manage-specialty",
  MANAGE_PATIENT: "/system/manage-patient",

  // Frontend
  SPECIALITY: "/chuyen-khoa",
  FACILITY: "/co-so-y-te/tat-ca",
  DOCTOR: "/bac-si",
  PACKAGE: "/dich-vu-y-te/kham-tong-quat",
  SUPPORT: "/ho-tro",
  HANDBOOK: "/cam-nang",
  CO_OPERATE: "/hop-tac",
  FOR_COMPANY: "/suc-khoe-doanh-nghiep",
  PACKAGE_FOR_COMPANY: "/goi-chuyen-doi-so",
  HIRE: "/tuyen-dung",
  FOR_PATIENT: "/danh-cho-benh-nhan",
  FOR_DOCTOR: "/danh-cho-bac-si",
  ROLE: "/vai-tro/bac-si-uy-tin",
  CONTACT: "/lien-he",
  FAQ: "/bac-si-thuong-hoi",
  TERMS: "/dieu-khoan-su-dung",
  COMPLAIN: "/thong-tin/quy-trinh-ho-tro-giai-quyet-khieu-nai",
  PROCEDURE: "/quy-che",
  REMOTE_CHECKUP: "/kham-tu-xa",
  DIAGNOSIS: "/dich-vu-y-te/xet-nghiem-y-hoc",
  MENTAL: "/kham-tinh-than",
  DENTIST: "/kham-nha-khoa",
  SURGERY: "/goi-phau-thuat",
  DIABETES: "/tieu-duong",
  TEST: "bai-test",
  NEAR_FACILITIES: "/y-te-gan-ban",
  DIRECTORY: "/danh-ba-y-te",
  PRIVACY: "/chinh-sach-bao-mat",
  APP: "/app",
  CALENDAR: "/lich-hen",
};
